### ISSUE TITLE
Oracle decentralization improvements

### ISSUE THREAD

**Issue by nostdm** [tokencard/contracts#231]
Based on the auditor comments and previous conversations, it might be a good idea to use an opt-in model for when we change the Oracle ENS target. So that the wallet points to the new oracle contract only once the user confirms the change. This would mean that we would need to reach out to all users when there's a critical upgrade so that they can update their contracts.

Alternative version of this could be a timed update with the option to opt-out before some deadline. So that when we change the Oracle ENS, the change will take effect in X amount of days, unless you specifically cancel the update.

**Comment by mischat** [comment]
On this topic, I don't think we need to have these safe guards in for the oracle. The worst case scenario is that we get the exchanges all wrong, which messes with our user's daily spend limits. I don't think this is a big issue for the moment.
