### ISSUE TITLE
Key Disclosure Attack Surface

### ISSUE THREAD

**Issue by i-stam** [tokencard/contracts#237]
Auditor's comment: A disclosure of the key associated with the address that manages the Controller ENS name, or the disclosure of any key associated with an address that passes onlyController() compromises Token Group Ltd.’s wallet administration infrastructure. A compromise of this nature would be able to lock funds in some wallets by inflating exchange rates such that no reasonable quantity of funds would pass the daily spend limit validation.
Mitigate the impact of a key disclosure: segregate the capabilities of privileged addresses such that the impact of any one key disclosure is minimized. Similarly, to the extent that the disclosure of one key could prove problematic, the architecture should rarely require the key to be used.

**Comment by mischat** [comment]
We have addressed this in version 2.0.X of our contracts. We now have a key hierarchy, whereby if a single controller gets compromised it can't do much damage. We can easily kick it out and further ... I guess the one thing we could do is make the manual override of the exchange rates in our oracle only be possible with our `admin` keys not the `controller` keys.... hrmm. I like this idea cc @i-stam ?

**Comment by mischat** [comment]
In the oracle, i think the following should be only admin: 
- updateCryptoCompareAPIPublicKey
- claim
- actually all of them ... 

Shouldn't holder be Controllable and then : 
- nonRedeemableTokens claim should be onlyAdmin
and then holder can be make NOT transferable ... 

Shouldn't licence be like above ^^

No change to the wallet 

In short, we should use the `Controller` for normal business work-flow and we should use the `admin` for admin / one-off tasks, i.e. one initiated by humans ... They admin addresses's private key should never be exposed to anything but a ledger and paper ...

**Comment by mischat** [comment]
@i-stam and @draganm thoughts ^^
