### ISSUE TITLE
Should this be something like SafeTokenTransfer

### ISSUE THREAD

**Issue by androolloyd** [tokencard/contracts#424]
https://github.com/tokencard/contracts/blob/068f1eec3c0992dbcefe9552dd133504dab1e44b/contracts/internals/claimable.sol#L39

Some ERC20 contracts don't return the proper status code's and as a result it seems that this method would fail with some improper implementations.

**Comment by i-stam** [comment]
Hi @androolloyd, thanks for spending time checking the contracts and for pointing this out! It is something that we are aware of (#419) and we have already addressed it in the following PRs:  #396 , #420. They will be merged soon and all the old contracts are going to be migrated. 
Thanks again and please feel free to open new issues if you think something needs to be fixed/updated. We strongly encourage this...

**Comment by mischat** [comment]
@androolloyd thanks for bringing this up, as mentioned above we have address this in the other version of the codebase we are supporting. the version 1.5.X branch which can be found in the https://github.com/tokencard/contracts/tree/release-branch and we have implemented all of this in the 2.1.X version of the code that can be found in master. This was picked up by the Audit we performed with the Trail of Bits. 

Thanks for sending this through, if you send me an email from the addy you are using on github, I would love to send you some TKN to say thanks. 

THANK YOU !

**Comment by androolloyd** [comment]
@mischat what email would you like to be contacted at? You can send it to my Monolith account :D

**Comment by mischat** [comment]
hey... you can mischa@monolith.xyz ;)

**Comment by mischat** [comment]
or why don't you share me a private gist ... that way i know it is you @androolloyd !

**Comment by mischat** [comment]
with your monolith contract address in the gist.
