### ISSUE TITLE
Emit an event the Holder Payable 

### ISSUE THREAD

**Issue by mischat** [tokencard/contracts#441]
And in all of the payables tbh. 

a la the Wallet

We use these to effeciently query the chain.

**Comment by mischat** [comment]
Thinking about this, I think we should clean this up a bit. 

We only need the event in the wallet, in the vault specifically.

**Comment by mischat** [comment]
am working on this too @i-stam

**Comment by i-stam** [comment]
the fallback in Holder is already payable

**Comment by mischat** [comment]
Yeah, I guess for the fallback's do we need to emit things ? I understand that we want to for the Wallet and for the Holder but not sure about the rest ... 

Wallet should be payable emit <-- make sure this is in the wallet and in the holder ?

License 
Oracle 
TokenWhitelist

**Comment by mischat** [comment]
only keep on Wallet and holder. Remove elsewhere
