### ISSUE TITLE
Wallet integer overflow from user input

### ISSUE THREAD

**Issue by nostdm** [tokencard/contracts#507]
The expression on line 695 of Wallet.sol uses the the value dataLength, which
is dervied from partially-trusted input, to compute i without performing appropriate
bounds checks.
```
assembly {
...
dataLength := mload(add(_transactionBatch, add(i, 52)))
...
}
...
i += 84 + dataLength;
```
If the input yielded a dataLength value of 2

256  ́ 84, for example, then the value
of i would be incremented by zero, and thus the code would loop forever. Other values

could cause the code to skip backwards through the input, or cause other counterintu-
itive behvaior.

Since the threat model for the Wallet contract includes key disclosure of the owner
account, inputs controlled by the owner account should not lead to unintended integer
overflows.
The code should include a bounds check for dataLength in each loop iteration
that bounds dataLength to the length of the input slice:

    require(i.add(dataLength) <= _transactionBatch.length);

**Comment by mischat** [comment]
Having looked at this today. 

It is our belief that if you could actually manage to cause this overflow, you would pop into an infinite loop as index becomes equal to zero which will terminate after the user runs out of gas. Which effectively could do nothing rinse the ETH on the owner address, which is an issue that is true.

That said we are interested to know how it would be possible to send this data to the EVM as we don’t think it would be possible to sign a transaction with data that large. We can only imagine that there is a way to send in corrupt data to the EVM which would trigger this overflow. Do you know of a way to do this? Or are we being defensive / cautious in our approach.
