### ISSUE TITLE
Wallet Owner Cannot Advance Signing Nonce

### ISSUE THREAD

**Issue by nostdm** [tokencard/contracts#510]
The relayNonce variable in Wallet.executeRelayedTransaction() enforces a
total ordering of owner-signed transactions in order to prevent those transactions from
being replayed. However, the owner account does not have a mechanism for advancing the nonce indepently, which means that if Token Group Ltd. ignores, drops, or other-
wise refuses to send a meta-transaction to the contract, it can never be independently cancelled. Since end-users may want stale meta-transactions to expire after some pe-
riod of time has elapsed, there should be functionality that allows the owner account to advance the relayNonce.

**Comment by mischat** [comment]
Indeed this doesn’t exist at the moment, we hadn’t thought of the scenario that we would take the signed package and do a runner and then broadcast it in the future. We will look at adding this in, thanks!
