### ISSUE TITLE
DailyLimit naming refactoring

### ISSUE THREAD

**Issue by i-stam** [tokencard/contracts#525]
- _updateAvailableDailyLimit -> resetAvailableAmount?

- updateTimestamp -> resetTimestamp?

- Events: SetDailyLimit() is now emitted from _modifyLimit -> ModifiedDailyLimit?

*Names tried to be kept the same for backwards compatibility.

**Comment by mischat** [comment]
I have the least opinion here, my guess is that @jeffreybolle would care the most :)

**Comment by i-stam** [comment]
They have been changed in v4 and they are not breaking the interface! They are internal variables.
