### ISSUE TITLE
Owner can be a smart contract

### ISSUE THREAD

**Issue by i-stam** [tokencard/contracts#570]
Currently, nothing prevents the owner from being a smart contract. In theory, this opens re-entrancy doors as the `onlyOwner()` modifier can be bypassed in this way. The `isContract()` check can be used in order to prevent this scenario.

**Comment by i-stam** [comment]
After examining the contracts carefully, we concluded that no extra damage (than by simply compromising the owner address) can be done by setting the owner as a smart contract.

**Comment by mischat** [comment]
We don't believe that there are any new attack vectors by having the owner as a smart contract.
